#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="${FR3_REPO_ROOT:-$HOME/FR3_CBF_Completion_Package_v1_1/FR3_CBF_Completion_Package_v1_1}";cd "$ROOT";mkdir -p logs/practical_architecture;STAMP="$(date -u +%Y%m%d_%H%M%S)";LOG="logs/practical_architecture/master_${STAMP}.log";exec > >(tee "$LOG") 2>&1
trap 'code=$?;echo;echo "PRACTICAL ARCHITECTURE DROP-IN: FAIL";echo "exit=$code command=${BASH_COMMAND:-unknown}";tail -n 360 "$LOG"||true;exit $code' ERR
export PYTHONHASHSEED=0 PYTHONDONTWRITEBYTECODE=1 OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1
echo '=================================================================';echo 'GENERIC 64T64R/HYBRID ARCHITECTURE + PHASE1 REVIEW CANDIDATE';echo '=================================================================';echo 'Execution: LOCAL WSL ONLY';echo 'No SSH, Slurm, Nibi, Narval, or MATLAB command will be run.';echo 'Campaign execution authorization: FALSE';echo 'Expected runtime: about 1 minute on the reference PC.'
for name in 00_preflight 10_run_validate 20_campaign_package 30_push;do wrapper="wrappers/practical_architecture/${name}.sh";wrapper_log="logs/practical_architecture/${name}.log";echo;echo "=== RUNNING $name ===";set +e;set -o pipefail;bash "$wrapper" 2>&1|tee "$wrapper_log";code=${PIPESTATUS[0]};set +o pipefail;set -e;printf '%s\n' "$code">"logs/practical_architecture/${name}.exitcode";echo "WRAPPER EXITCODE: $name=$code";[[ $code -eq 0 ]]||exit "$code";done
COMMIT="$(git rev-parse HEAD)";REVIEW="$ROOT/evidence/practical_architecture_mapping_v1/FR3_PRACTICAL_ARCHITECTURE_PHASE1_REVIEW_v1.zip";echo '=================================================================';echo 'PRACTICAL ARCHITECTURE + PHASE1 PREP DROP-IN: PASS';echo "Commit: $COMMIT";echo "Commit URL: https://github.com/afazeliUofT/FR3_CBF_Completion_Package_v1_1/commit/$COMMIT";echo "Review bundle: $REVIEW";echo "Review bundle SHA-256: $(sha256sum "$REVIEW"|awk '{print $1}')";echo 'Execution performed: LOCAL WSL ONLY';echo 'Nibi submission performed: NO';echo 'Campaign execution authorized: NO';echo 'Next gate: ACQUIRE_FOUR_ADDITIONAL_PROTECTED_PASS_RECORDS_AND_INDEPENDENTLY_REVIEW_PHASE1_CAMPAIGN_CANDIDATE';echo '================================================================='
if command -v explorer.exe >/dev/null 2>&1;then explorer.exe "$(wslpath -w "$(dirname "$REVIEW")")" >/dev/null 2>&1||true;fi
