#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,math
from pathlib import Path
import numpy as np,pandas as pd,yaml
ROOT=Path(__file__).resolve().parents[1]
def write_json(p,o): p.write_text(json.dumps(o,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def main()->int:
 ap=argparse.ArgumentParser(); ap.add_argument('--config',default='config/e3_first_sector_p452.yaml'); args=ap.parse_args(); cfg=yaml.safe_load((ROOT/args.config).read_text()); d=ROOT/cfg['outputs']['work_dir']; expected=cfg['expected']
 prep=json.loads((d/'FIRST_SECTOR_P452_PREP_AUDIT.json').read_text()); ma=json.loads((d/'P452_FIRST_SECTOR_MATLAB_AUDIT.json').read_text()); audit=json.loads((d/'FIRST_SECTOR_P452_AUDIT.json').read_text()); loss=pd.read_csv(d/'p452_basic_loss.csv'); coupling=pd.read_csv(d/'p452_coupling_export.csv'); es=pd.read_csv(d/'earth_station_gain_timeseries.csv'); bs=pd.read_csv(d/'bs_gain_accounting.csv'); ts=pd.read_csv(d/'gain_accounting_timeseries.csv.gz'); summary=pd.read_csv(d/'conditional_threshold_summary.csv')
 assert prep['status']=='MATLAB_READY_FROZEN'; assert ma['status']=='PASS'; assert audit['status']=='ACCOUNTING_READY_FOR_VALIDATION'; assert ma['matlab_release']==str(expected['matlab_release']); assert ma['p452_reference_commit']==str(expected['p452_reference_commit']); assert ma['sector_id']==str(expected['sector_id'])
 expected_loss=len(cfg['propagation']['time_percentages'])*len(cfg['propagation']['polarization_codes'])*len(cfg['propagation']['coast_distance_scenarios_km']); assert len(loss)==expected_loss; assert len(coupling)==expected_loss
 calc=10**(-loss.basic_transmission_loss_db.to_numpy(float)/10); assert np.allclose(calc,loss.path_gain_linear.to_numpy(float),rtol=2e-12,atol=0)
 assert set(loss.polarization_code.astype(int))==set(map(int,cfg['propagation']['polarization_codes'])); assert set(np.round(loss.time_percentage,12))==set(np.round(cfg['propagation']['time_percentages'],12)); assert set(np.round(loss.coast_distance_km,12))==set(np.round(cfg['propagation']['coast_distance_scenarios_km'],12))
 assert len(es)==int(expected['protected_window_sample_count'])*6; assert len(bs)==3; expected_ts=int(expected['protected_window_sample_count'])*len(cfg['propagation']['time_percentages'])*len(cfg['propagation']['polarization_codes'])*3*2; assert len(ts)==expected_ts
 assert np.isfinite(ts.conditional_interference_dbw_per_10mhz).all(); assert abs(float(audit['earth_station_minimum_off_axis_deg'])-8.035691596201232)<1e-7; assert abs(float(audit['earth_station_maximum_aggregate_gain_dbi'])-6.374418487486793)<1e-7
 bw=10*math.log10(float(cfg['power_accounting']['protected_bandwidth_mhz'])/float(cfg['power_accounting']['reference_bandwidth_mhz'])); assert abs(float(audit['bandwidth_adjustment_db'])-bw)<1e-12; coherent=bs.loc[bs.gain_case=='COHERENT_ARRAY_UPPER_ENVELOPE'].iloc[0]; elem=bs.loc[bs.gain_case=='ELEMENT_PATTERN_REFERENCE'].iloc[0]; assert abs(float(coherent.bs_gain_dbi)-float(elem.bs_gain_dbi)-10*math.log10(256))<1e-10
 sample=ts.iloc[::max(1,len(ts)//1000)].copy(); recomputed=sample.conducted_power_dbw_per_100mhz+sample.bandwidth_adjustment_db+sample.activity_adjustment_db+sample.bs_gain_dbi-sample.basic_transmission_loss_db+sample.earth_station_gain_dbi-sample.polarization_mismatch_loss_db; assert np.allclose(recomputed,sample.conditional_interference_dbw_per_10mhz,rtol=0,atol=1e-10)
 assert set(coupling.element_gain_accounted.astype(str).str.lower())<={'false','0'}; assert (coupling.receiver_gain_linear==1).all(); assert coupling.provenance_note.str.contains('NOT_PAPER_RESULT').all()
 val={'status':'PASS','claim_boundary':cfg['claim_boundary'],'sector_id':expected['sector_id'],'matlab_release':ma['matlab_release'],'p452_reference_commit':ma['p452_reference_commit'],'p452_basic_loss_rows':len(loss),'gain_accounting_rows':len(ts),'protected_samples':int(expected['protected_window_sample_count']),'basic_loss_conversion_verified':True,'external_gain_identity_verified':True,'zero_terminal_gains_inside_p452_verified':True,'no_separate_p2108_baseline_verified':True,'h_v_branches_separate_verified':True,'time_accounting_not_frozen_verified':str(cfg['protection']['time_accounting_status']).startswith('NOT_FROZEN'),'review_required':True,'next_gate':'HUMAN_REVIEW_OF_ONE_SECTOR_ACCOUNTING_AUDIT'}; write_json(d/'FIRST_SECTOR_P452_VALIDATION.json',val); (d/'FIRST_SECTOR_P452_VALIDATION.md').write_text(f"# First-sector P.452 validation\n\n- Status: `PASS`\n- Sector: `{expected['sector_id']}`\n- P.452 rows: `{len(loss)}`\n- Gain-accounting rows: `{len(ts)}`\n- Protected samples: `{expected['protected_window_sample_count']}`\n- MATLAB: `{ma['matlab_release']}`\n- P.452 commit: `{ma['p452_reference_commit']}`\n\nBoth the basic-loss and external gain-accounting identities passed. The result remains a one-sector accounting audit, not paper evidence.\n",encoding='utf-8')
 print('FIRST-SECTOR P.452 BASIC-LOSS VALIDATION: PASS'); print('FIRST-SECTOR GAIN-ACCOUNTING VALIDATION: PASS'); print('Sector:',expected['sector_id']); print('P.452 rows:',len(loss)); print('Gain-accounting rows:',len(ts)); print('Protected samples:',expected['protected_window_sample_count']); print('Claim boundary:',cfg['claim_boundary']); print('Next gate:',val['next_gate']); return 0
if __name__=='__main__': raise SystemExit(main())
